---
- hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Update package cache
      yum:
        update_cache: yes

  tasks:
    - name: Add EPEL repository
      yum_repository:
        name: epel
        description: Extra Packages for Enterprise Linux 7 - $basearch
        baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
        gpgcheck: yes
        gpgkey: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
        enabled: yes

    - name: Install required packages
      yum:
        name:
          - epel-release
          - nrpe
          - nagios-plugins-all
          - bind
          - bind-utils
          - ntp
          - httpd
          - openssl
          - mod_ssl
          - nfs-utils
          - autofs
          - openldap-clients
          - nss-pam-ldapd
          - authconfig
          - man
          - man-pages
          - mlocate
          - sysstat
          - htop
          - git
          - vim
          - net-tools
        state: present
      ignore_errors: yes

    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - named
        - ntpd
        - httpd
        - nfs
        - autofs
        - nrpe
