---
- hosts: myhosts
  become: yes
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest
  - name: Starting service and enable 
    service:
      name: httpd
      state: started
      enabled: yes 
