---
- name: Install packages on CentOS
  hosts: web
  become: true
  vars: 
    packages: 
      - httpd
      - mysql
      - php
    
    tasks:
      - name: Install Lamp packages 
        yum: 
          name: "{{item}}"
          state: present
        loop: "{{packages}}"
